### ISSUE TITLE
obsolete YRpmGroupsTree does not allow to build bindings with warning as error

### ISSUE THREAD

**Issue by anaselli** [libyui/libyui-bindings#34]
```
/usr/include/yui/YRpmGroupsTree.h:39:4: warning: #warning The YRpmGroupsTree class is obsolete. DO NOT USE ANYMORE. [-Wcpp]
 #  warning The YRpmGroupsTree class is obsolete. DO NOT USE ANYMORE.
```

**Comment by shundhammer** [comment]
The only reason why this class is still there is libyui-gtk-pkg. Is this still relevant?

**Comment by anaselli** [comment]
I don't know anything about libyui-gtk-pkg... 

if you definitely remove YRpmGroupsTree i will do it into libyui-gtk too.

**Comment by shundhammer** [comment]
I think we can safely remove it in libyui-bindings; it was never intended to be used outside of a subclass of YPackageSelector.

**Comment by shundhammer** [comment]
I just removed it from the bindings as part of https://github.com/libyui/libyui/pull/19 .
